import type { Metadata } from "next";
import "./globals.css";
import { getSiteUrl } from "@/lib/env";

const siteUrl = getSiteUrl();

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "Black Pick — Who Is The Pick?",
    template: "%s | Black Pick",
  },
  description: "Black Combat fight prediction platform. Predict fights, build your record, prove you know the game.",
  openGraph: {
    type: "website",
    siteName: "Black Pick",
    title: "Black Pick — Who Is The Pick?",
    description: "Black Combat fight prediction platform. Predict fights, build your record.",
    url: siteUrl,
    // OG image is auto-generated by app/opengraph-image.tsx (file convention).
    // No explicit `images` needed — Next.js wires it automatically.
  },
  twitter: {
    card: "summary_large_image",
    title: "Black Pick — Who Is The Pick?",
    description: "Black Combat fight prediction platform.",
    // Falls back to the OG image (file convention).
  },
  robots: {
    index: process.env.NODE_ENV === "production",
    follow: process.env.NODE_ENV === "production",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // html/body is rendered by [locale]/layout.tsx for dynamic lang attribute
  return children;
}
